site_name: C++ 入门 | Cpp-Introduction
site_url: http://cpp-intro.readthedocs.io/
repo_url: https://github.com/WorldHim/Cpp-Intro
site_description: C++ 入门 | Cpp-Introduction
site_author: WorldHim

copyright: Copyright © 2022 [WorldHim](http://cpp-intro.readthedocs.io/)

nav:
  - 主页 Home: index.md
  - 关于 About: about.md

theme:
  name: material
  locale: zh-CN

plugins:
  - search:
  - git-revision-date-localized
  - git-authors
  - git-committers:
  - git-latest-release
  - macros


markdown_extensions:
  - extra
  - admonition
  - meta
  - sane_lists
  - smarty
  - toc:
    permalink: "#"
  - wikilinks