site_name: C++ 入门 | Cpp-Introduction
site_url: http://cpp-intro.readthedocs.io/zh-CN/latest
repo_url: https://github.com/WorldHim/Cpp-Intro
site_description: C++ 入门 | Cpp-Introduction
site_author: WorldHim
copyright: Copyright &copy; 2022 [WorldHim](http://cpp-intro.readthedocs.io/)

nav:
  - 主页 Home: index.md
  - 关于 About: about.md

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到深色模式
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide

extra:
  generator: true
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 繁体中文
      link: /zh-Hant/ 
      lang: zh-Hant
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/WorldHim
      name: WorldHim on Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/565437509
      name: WorldHim on Bilibili
  consent:
    title: Cookie 同意书
    description:
      我们使用 Cookie 来识别您的重复访问和偏好，以衡量我们文档的有效性，以及用户是否找到他们正在搜索的内容，并且您能够随时更改您的 Cookie 设置。如果您同意，感谢您帮助我们改进我们的文档

plugins:
  - search: {
    separator: '[\s\u200b\-]'
  }
  - git-revision-date-localized
  - git-authors
  - git-committers: {
    repository: worldhim/cpp-intro,
    branch: main
  }
  - git-latest-release
  - macros
  - tags

markdown_extensions:
  - extra
  - admonition
  - meta
  - md_in_html
  - sane_lists
  - smarty
  - toc: {
    permalink: "#"
  }
  - wikilinks