site_name: C++ 入门 | Cpp-Introduction
site_url: http://cpp-intro.readthedocs.io/
copyright: Copyright © 2022 [WorldHim](http://cpp-intro.readthedocs.io/)

nav:
  - 主页 Home: index.md
  - 关于 About: about.md

theme:
  name: material

plugins:
  - search:
  	lang: zh-cn


markdown_extensions:
  - extra
  - admonition
  - meta
  - sane_lists
  - smarty
  - toc: {
    permalink: "#"
  }
  - wikilinks